apiVersion: v1
kind: Pod
metadata:
  name: takos
spec:
  replicas: 6
  selector:
    matchLabels:
      app: takos
  template:
    metadata:
      labels:
        app: takos
    spec:
      containers:
      - name: takos
        image: takoserver/takos:latest
        ports:
        - containerPort: 80